services:
  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "1000:1000"
    command: uvicorn main:app --host 0.0.0.0 --port 1000

  frontend:
    build:
      context: ./frontend
      dockerfile: frontend.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:1000}
    ports:
      - "3000:3000"
    depends_on:
      - backend
